# Generated by Django 5.2.9 on 2025-12-13 08:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('sharif', models.CharField(max_length=200)),
                ('familiya', models.CharField(max_length=200)),
                ('tugilgan_sana', models.DateField()),
                ('jins', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('tugilgan_joyi', models.CharField(max_length=100)),
                ('fuqarolik', models.CharField(max_length=100)),
                ('pasport_seriya', models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', message='Pasport seriyasi 2 ta bosh harf bolishi kerak.')])),
                ('pasport_raqam', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999)])),
                ('pasport_berilgan_joy', models.CharField(max_length=200)),
                ('pasport_berilgan_sana', models.DateField()),
                ('soliq_raqami', models.CharField(max_length=20)),
                ('yashash_manzili', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('ijtimoiy_tarmoq', models.CharField(max_length=100)),
                ('aloqa_usuli', models.CharField(max_length=50)),
                ('oilaviy_holat', models.CharField(max_length=50)),
                ('turmush_ortogi_haqida', models.CharField(blank=True, max_length=200, null=True)),
                ('farzandlar_soni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('farzandlar_haqida', models.CharField(blank=True, max_length=200, null=True)),
                ('nogironlik_holati', models.CharField(blank=True, max_length=100, null=True)),
                ('imtiyozlar', models.CharField(blank=True, max_length=200, null=True)),
                ('diplom_malumotlari', models.CharField(max_length=200)),
                ('maxsus_kurslar', models.CharField(blank=True, max_length=200, null=True)),
                ('sertifikatlar', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('til_bilish_darajasi', models.CharField(max_length=200)),
                ('kompyuter_konikalari', models.CharField(blank=True, max_length=255, null=True)),
                ('kasbiy_konikalari', models.CharField(max_length=200)),
                ('haydovchilik_guvohnomasi', models.CharField(blank=True, max_length=100, null=True)),
                ('lavozim', models.CharField(max_length=100)),
                ('bolim', models.CharField(max_length=100)),
                ('rahbar', models.CharField(max_length=100)),
                ('shartnoma_turi', models.CharField(choices=[('full_time', 'Toliq stavka'), ('part_time', 'Qisman stavka'), ('temporary', 'Vaqtinchalik'), ('hourly', 'Soatbay')], max_length=100)),
                ('davomat', models.CharField(max_length=200)),
                ('tarif_razryad', models.CharField(max_length=100)),
                ('oylik', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ish_holati', models.CharField(choices=[('active', 'Ishda'), ('inactive', 'Faol emas'), ('fired', 'Ishdan boshatilgan'), ('vacation', 'Ta’tilda')], max_length=50)),
                ('ish_soatlari', models.CharField(max_length=100)),
                ('smena_raqami', models.IntegerField()),
                ('time_tracker_holati', models.CharField(max_length=100)),
                ('tatil_holati', models.BooleanField(default=False)),
                ('tatil_boshlanish_sana', models.DateField(blank=True, null=True)),
                ('tatil_tugash_sana', models.DateField(blank=True, null=True)),
                ('kasallik_kunlari', models.IntegerField(blank=True, null=True)),
                ('mehnat_shartnomasi', models.FileField(blank=True, null=True, upload_to='documents/contracts/')),
                ('lavozim_instruksiyasi', models.FileField(blank=True, null=True, upload_to='documents/job_instructions/')),
                ('pasport_nusxasi', models.FileField(blank=True, null=True, upload_to='documents/passports/')),
                ('diploma_nusxasi', models.FileField(blank=True, null=True, upload_to='documents/diplomas/')),
                ('tibbiy_kitobcha', models.FileField(blank=True, null=True, upload_to='documents/medical_books/')),
                ('arizalar_tarixi', models.TextField(blank=True, null=True)),
                ('intizomiy_protokollar', models.FileField(blank=True, null=True, upload_to='documents/disciplinary/')),
                ('oldingi_ish_joylari', models.TextField(blank=True, null=True)),
                ('stajirovka_tajriba', models.TextField(blank=True, null=True)),
                ('lavozimlar_tarixi', models.TextField(blank=True, null=True)),
                ('rotatsiyalar_va_otkazmalar', models.TextField(blank=True, null=True)),
                ('kpi_korsatkichlari', models.TextField(blank=True, null=True)),
                ('oylik_natijalar', models.TextField(blank=True, null=True)),
                ('samaradorlik_indeksi', models.FloatField(blank=True, null=True)),
                ('bonuslar_va_motivatsiya', models.TextField(blank=True, null=True)),
                ('oxirgi_tibbiy_korik_sana', models.DateField(blank=True, null=True)),
                ('zararli_ishga_ruxsat', models.BooleanField(default=False)),
                ('emlash_holati', models.CharField(blank=True, max_length=255, null=True)),
                ('kirish_karta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('avtotransport_ruhsatnomasi', models.CharField(blank=True, max_length=100, null=True)),
                ('bino_kirish_huquqlari', models.CharField(blank=True, max_length=255, null=True)),
                ('it_tizim_loginlari', models.TextField(blank=True, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('director', 'Direktor'), ('teacher', 'Oqituvchi'), ('admin', 'Admin')], default='admin', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
